services:
  - type: web
    name: liner-measure
    env: python
    buildCommand: "apt-get update && apt-get install -y tesseract-ocr && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
